### ISSUE TITLE
AA Crashes in t43 under Optimistic Economic Scenario / Inputs

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#47] opened 2016-07-21 17:35 UTC
In the two optimistic economic scenarios that the SWIM team has run to-date, AA crashes at approximately t43 (2033) with the following error message:

```
22-Jun-2016 14:18, INFO, 22-Jun-2016 14:18, ERROR, Overflow error in CUBuy, CUSell calcs com.hbaspecto.pecas.OverflowException: com.hbaspecto.pecas.ChoiceModelOverflowException: CommodityZUtilityError for SellingZUtilityPECASZone:1 Capital Transfer Receipts
22-Jun-2016 14:18, INFO, com.hbaspecto.pecas.OverflowException: com.hbaspecto.pecas.ChoiceModelOverflowException: CommodityZUtilityError for SellingZUtilityPECASZone:1 Capital Transfer Receipts
```

We need to track this down and understand how to correct the Optimistic economic scenario so that it can complete successfully.

**Comment by gregmacfarlane** [comment] 2016-11-01 18:22
This is a duplicate of #46.

**Closed by gregmacfarlane** 2016-11-01 18:22 UTC
Labels: blocker
