### ISSUE TITLE
add distance, time, weight to Trips_CTTruck.csv output file

### ISSUE THREAD

**Issue by bstabler** [pbsag/tlumip#39] opened 2016-03-10 23:27 UTC
@bettinardi would like to add this to the output file

**Comment by bettinardi** [comment] 2016-03-16 22:35
I would add that it is a little higher priority than a "like", Becky and I really NEED that information to use the output from CT effectively.

**Comment by bettinardi** [comment] 2016-08-11 17:24
@gregmacfarlane - can you remind me why we weren't able to address / close this issue.  Is this something that we can fix before the end of TLUMIP 5.  We really need CT to export the specified fields.

**Comment by gregmacfarlane** [comment] 2016-08-12 14:13
@rickdonnelly remembers why. Can he answer?

**Comment by gregmacfarlane** [comment] 2016-08-31 23:03
@rickdonnelly and I had a conversation this afternoon. We cannot put the weight on the output file because we do not carry commodities or quantities of them through the local CT process. The data to do this simply do not exist anywhere. He can explain more as warranted.

He and I will sit down together (on a screenshare) and put the time and distance fields on the output file next week.

**Comment by bettinardi** [comment] 2016-08-31 23:04
what about adding value - or anything about what is in the truck - would that be possible?  How are the trucks distributed if we don't know what they are carrying?

**Comment by gregmacfarlane** [comment] 2016-09-01 13:07
For local trucks, we do not know what they are carrying; the commodity skims coming from AA did not make any kind of logical sense, and there is no data on which to build imputation methodologies. As @rickdonnelly explained it to me, we could have a model where we knew what trucks were carrying, or a model where observed patterns in the transportation system were replicated, but not both.

**Comment by rickdonnelly** [comment] 2016-09-01 14:29
@gregmacfarlane gave you the short answer, and here I'll sketch out the long version for those who care. The problem is even more pervasive than just the particular implementation of CT that we're using. Even if we knew the commodity the truck was carrying (in addition to truck type, which we do know), we still could not know the weight or value of the shipment. If we think in terms of discrete firms, we can allocate portions of the FAF inter-regional commodity flows by mode and commodity to them, based upon the make and use coefficients that AA pumps out (which look reasonable to me). We could likewise allocate a portion of the AA production-consumption flows to them, based upon their NAICS code and size, enabling us to know the total value of intra-regional transactions for each synthetic firm (i.e., between that firm and other Oregon firms and households). Thus: we'd have:

+ Value, tonnage, and truckload equivalents (including empties) of inter-regional (long-distance) commodities by mode from the FAF
+ Value of production and consumption of intra-regional (within Oregon) commodities from AA

So at this point we could say something about total commodities flowing into and out of each synthetic firm. But there are two obstacles to overcome before we could attribute those flows to the truck tours generated by CT. The firm presumably combines all of the consumed (transportable) commodities with labor, capital assets, information, and business processes in order to produce output. The transportable commodities are variable inputs, while the others are usually fixed factors of production. Some of those commodities are consumed in production, such that the volume of output is smaller and of different density than inputs. Electronic fabrication plants consume a great deal of inputs, but produce (ship) very small and lightweight boards (and a lot of waste products). Food distribution centers, on the other hand, distribute the same volume of commodities it consumes, albeit in different quantities and frequencies. The bottom line for us is that we don't know how much of the consumed commodities leave the firm, or even if they do at all (e.g., an auto upholstery firm consumes textiles and chemicals, but produces auto parts). We can guess at this, perhaps just randomly assigning a commodity based upon the make coefficients for that particular firm. I haven't done that, because that tells me the value of what is produced, but not the weight. 

But even if I we assumed that the proportions of commodities gleaned from the make coefficients for that industry (NAICS code) correctly represented the volume of commodities shipped we still cannot get to shipment weight, for no one has data on distribution of, or even just mean values of, urban truck weights. We have a lot of data on average payload size for inter-regional flows, based upon truck intercept surveys at weigh stations. But those are for combination trucks moving long distances. Data on lightweight commercial vehicles (e.g., pick-up trucks, vans, SUVs) and single unit trucks, which account for the majority of both CV trips and VMT within urban areas, are non-existent.

We're schemed about using portable WIM for measure truck weights within urban areas, but I've never succeeded at getting a state DOT to do that for me. Bill Upton and I worked hard to get ODOT to deploy portable WIM in Portland during TLUMIP2, to not avail. But even if we had succeeded we'd have learned only about the distribution of weight by truck classification. We'd of course still know nothing about what was in the truck. In the end we concluded that it would be a lot of work to collect these data, but that if we applied those distributions in CT (still in the future at that point) we'd only be correct about total tonnage moved by light and single-unit trucks in aggregate. But most of our use cases were for specific corridors, where we'd have zero confidence in the weights attributed to the small number of trucks moving through that corridor. We felt it was better to report no data at all, rather than data we know was not accurate at the likely levels it was desired for. We made that decision back in 2004 or so, but it seems still valid today.

**Comment by bettinardi** [comment] 2016-09-01 14:40
All that is very helpful and I more fully understand the issues surrounding this now - thank you for that context.  

One last question if I may - do we know how SWIM 2.0 CT was adding value and weight to the trucks?  Based on the explanation above, I'm now understanding that those values were likely total garbage, I'm just curious how the previous CT was collecting and assembling that garbage.

**Comment by gregmacfarlane** [comment] 2016-09-08 12:35
This is added as of 5a4c4c1eb532fedf65aa3860fd7811524f7dad2b; will need to resolve #56 before closing this one.

**Comment by rickdonnelly** [comment] 2016-09-08 13:08
@bstabler: The last version of CT mapped the production of firms, provided by AA in annual dollar terms, to commodities in local trucks by using average payload weights by commodity and truck type from the 2002 VIUS microdata (which reported them in very broad ranges) and the 1999-2001 Commercial Vehicle Survey from Canada. We have no way of validating the resulting value and tonnage, but at least it was internally consistent. If production in a given alpha zone was forecasted to grow by 20 percent over the base year then 1.2 times more trucks would be generated in total, which we'd convert into discrete trucks with the same characteristics. I did not carry this mapping over to the current version because the data just seem shaky to me. If we had an establishment survey to base those numbers on I'd have a lot more confidence in them. Putting those estimates back in should be straight-forward, and they'd be plausible estimates, but there would be a lot riding on AA production-consumption flow matrices being right.

**Comment by bettinardi** [comment] 2016-09-13 21:50
The fields; trip mode (all 9), tour mode (all 9), and truck ID (just a sequential record count) should all be dropped from Trips_CTTruck.csv if they are going to remain as-is, and not provide any information about the specific truck trip record.

**Closed** 2017-01-31 19:59 UTC
